### ISSUE TITLE
🐛 MacOS Support for `gcp_scanner` development

### ISSUE THREAD

**Issue by peb-peb** [google/gcp_scanner#125]
As discussed in PR #123 [here](https://github.com/google/gcp_scanner/pull/123/files#r1153606737).

What should be the recommended development environment for MacOS.
Currently, the tool supports **linux**. So, `wsl` makes it possible to develop it on windows too.

If any solutions are found, they should be added to the appropriate docs.

**Comment by Bhardwaj-Himanshu** [comment]
Hi @peb-peb,
Read on to the issue as mentioned here, just wanted to clarify if you still needed some help on this issue.
Had some queries in mind, will go as follows:
-Is this question regarding, how can someone clone and set up the codebase as well as environment up and running on macos?
OR
-Regarding the development of a application/package for mac-os operating systems, so that users on mac-os are able to easily install and setup the gcp_scanner.

Also, do let me know if I should move this comment to #123, didn't moved it there initially because did'nt want to make it cluttered!
Thanks.

**Comment by peb-peb** [comment]
> -Is this question regarding, how can someone clone and set up the codebase as well as environment up and running on macos?

Yes, it's regarding the environment setup for the development of GCP_Scanner on MacOS. This should be documented in the `INSTALL.md` doc.
