### ISSUE TITLE
Fix unit_test failure

### ISSUE THREAD

**Issue by mshudrak** [google/gcp_scanner#13]
Our most up-to-date test [fails](https://github.com/google/gcp_scanner/actions/runs/3952114177/jobs/6766801093) with the following error
```

The following line was not identified in the output:
                "compute.googleapis.com/quota/local_ssd_total_storage_per_vm_family/exceeded"

The following line was not identified in the output:
                "compute.googleapis.com/quota/local_ssd_total_storage_per_vm_family/usage"

The following line was not identified in the output:
                "file.googleapis.com/nfs/server/connections"

The following line was not identified in the output:
                "logging.googleapis.com/billing/ingested_bytes"
```

It seems like Compute Engine API, File and Logging has changed. We need to mark corresponding lines as volatile and check that test is passing.

**Comment by smallChenn** [comment]
it looks like more tests are failed since then, I just run a dry run in my local machine and two tests failed, which matches the latest [test.](https://github.com/google/gcp_scanner/actions/runs/4249419933)

 I can take on this issue if it's open

**Comment by mshudrak** [comment]
Thanks, assigning this one to you.

**Comment by mshudrak** [comment]
We have a lot of interest from other members of community. So, I will drop assignees for all bugs, so anyone can work on them.

**Comment by ZhengLin-Li** [comment]
I checked the GitHub Action Log [here](https://github.com/google/gcp_scanner/actions/runs/4264872005/jobs/7423508061) and discovered that we now have 27 projects rather than 26. Is this correct? If that's the case, I'll fix this issue first.
![image](https://user-images.githubusercontent.com/63448884/221333227-5090dd40-0bc0-44da-bf2f-34798dedfbeb.png)

![image](https://user-images.githubusercontent.com/63448884/221333242-5a219880-ede8-4136-a352-59398e225198.png)
